### ISSUE TITLE
Add Makefile.am to man directory

### ISSUE THREAD

**Issue by andy5995** [theimpossibleastronaut/modemu2k#15]
There should be a Makefile.am in the man directory that will install man pages.

This one can be adapted to do that:

https://github.com/theimpossibleastronaut/rmw/blob/master/man/Makefile.am

The main difference is that the files have different extensions and aren't in separate directories; therefore the names of the variables will have to be changed.

@Erick2280 are you interested in trying this?

**Comment by Erick2280** [comment]
Of course! I will take a look on this.

**Comment by andy5995** [comment]
Oh, here is the link! https://gitter.im/modemu2k/Lobby#
