### ISSUE TITLE
Unable to connect with modemu2k-0.0.5

### ISSUE THREAD

**Issue by aianson** [theimpossibleastronaut/modemu2k#25]
modeumk2k-0.0.5 doesn't seem to work for me here.

I saw your slackbuild for modemu2k so I grabbed it and installed it here on a fresh slackware64 install. It built and installed fine. It runs fine along with minicom but doesn't connect to the remote host.

I uninstalled 0.0.5 and used the slackbuild script (just editing the version) to build 0.0.4 and that does work for me.

I have a dual stack here, IPv4 and IPv6.

Sorry for the vague report, I'm not sure what's happening.

**Comment by andy5995** [comment]
My first guess would be you'll need to change the format for specifying the port... note the [ReleaseNotes](https://github.com/theimpossibleastronaut/modemu2k/blob/v0.0.5/ReleaseNotes)...

Are you using `host[:port]` or `host [port]`. If you're not using any port, then it should default to 23 and work; if it doesn't, I did something wrong. :)

Changing the way the port is specified was needed to allow IPv6 hosts to be specified. At least, I knew of no other way to do it.

>I have a dual stack here, IPv4 and IPv6.

I tested with ipv4 and ipv6 but separately. If the port isn't the problem, I may need to add some code to "force" one or the other. Like `telnet` has an option to force one or the other.

**Comment by aianson** [comment]
> My first guess would be you'll need to change the format for specifying the port... note the [ReleaseNotes](https://github.com/theimpossibleastronaut/modemu2k/blob/v0.0.5/ReleaseNotes)...
> 
> Are you using `host[:port]` or `host [port]`. If you're not using any port, then it should default to 23 and work; if it doesn't, I did something wrong. :)
> 
> Changing the way the port is specified was needed to allow IPv6 hosts to be specified. At least, I knew of no other way to do it.

Oh.. I missed that detail.. :)

I have installed 0.0.5 now and updated my dialing directory. My own BBS is on port 2030 so I needed to change it. Working fine now.. thanks!

**Comment by andy5995** [comment]
You're welcome! Very glad it was an issue easy to solve ;)

Thanks for reaching out.

I've "pinned" the issue to make it more visible in case that affects anyone else.

You're welcome to make a pull request to add your BBS to the README, there's a short section at the bottom reserved for that.

**Comment by aianson** [comment]
On Thu, 29 Aug 2019 16:06:23 -0700
Andy Alt <notifications@github.com> wrote:
 
> I've "pinned" the issue to make it more visible in case that affects anyone else.

Yep, likely a good idea.. :)

> You're welcome to make a pull request to add your BBS to the README, there's a short section at the bottom reserved for that.

I get a fair bit of source from github but I have never used anything other than git clone so I don't know what a pull request is or how to go about it. I wouldn't mind adding my BBS to the README but I fear the unknown. My BBS is called The Rusty MailBox and is available 24/7/365 (except for maintenance times) at trmb.ca on port 2030 if you would like to add it.. :)

**Comment by andy5995** [comment]
No problem. Done. :)
