### ISSUE TITLE
a "--help" argument needs to be added

### ISSUE THREAD

**Issue by andy5995** [theimpossibleastronaut/modemu2k#3]
https://github.com/theimpossibleastronaut/modemu2k/blob/3e0ab8e3200718c556b5af7647e7d81c284dcf37/src/cmdarg.c#L48

**Comment by linton-dawson** [comment]
Hello ! I'm interested in working on this issue. Could you please elaborate the issue though ? I am fairly new to this.

**Comment by andy5995** [comment]
Hi @linton-dawson 

If you build the program, and give it the `--help` option, it will spit out the message that it's an invalid option. When `--help` is given, it should show the usage.

It should do the same thing as when `-h` is given.

**Comment by andy5995** [comment]
One way to do it would be to use getopt.h

This is an example of a program getting command line options when the getopt.h header is included

https://github.com/theimpossibleastronaut/rmw/blob/9119b23b3e5a89379ab0f9624496481bd8acbb9e/src/rmw.c#L66

That single line would mean that  `--help` would be accepted, or `-h`
