### ISSUE TITLE
modemu2k segfaults when started

### ISSUE THREAD

**Issue by aianson** [theimpossibleastronaut/modemu2k#39]
I am getting a segfault when starting modemu2k.

alan@irondust:~$ modemu2k
modemu2k 0.0.6
Enter 'at%q' to quit

Segmentation fault
alan@irondust:~$ 

I built this modemu on slackware-15.0 using the SlackBuild from slackbuilds.org.

I am not sure why that happens or what my next steps should be. Help!

**Comment by andy5995** [comment]
@aianson Thanks for the report! I'll check it out very soon.

You could try building the git version from source. I think the only dependencies you'd need to install is meson and ninja (build instructions on the README).

If that works ok for you on Slackware, I'll probably do a release.

If you don't wanna do that, no worries. I'll see what's up with v0.0.6 on Slack.

**Comment by aianson** [comment]
On Mon, 08 Aug 2022 17:55:01 -0700
Andy Alt ***@***.***> wrote:

> @aianson Thanks for the report! I'll check it out very soon.
> 
> You could try building the git version from source.

I tried this but I couldn't get either meson on ninja happy with my setup, I'm going to keep hacking away.. :)

> I think the only dependencies you'd need to install is meson and ninja (build instructions on the README).

meson-0.59.4 and ninja-1.10.2 are in slackware-15.0.

> If that works ok for you on Slackware, I'll probably do a release.

I must be doing something wrong. Either I am not reading it right or I am misunderstanding something. Can you list the instructions for me? What directory to create and what commands to give. I am missing something, but I'm not sure what.

> If you don't wanna do that, no worries. I'll see what's up with v0.0.6 on Slack.

No worries, I'll try to get it running here and let you know my experience.

I built 0.0.6 without the slackbuild and that does run without seg-faulting. I'm not sure what the difference is but it also doesn't work for me. The reason is unknown at this point.

**Comment by andy5995** [comment]
> On Mon, 08 Aug 2022 17:55:01 -0700 Andy Alt ***@***.***> wrote: @aianson Thanks for the report! I'll check it out very soon. You could try building the git version from source.
> I tried this but I couldn't get either meson on ninja happy with my setup, I'm going to keep hacking away.. :)

What's the exact output?

> I must be doing something wrong. Either I am not reading it right or I am misunderstanding something. Can you list the instructions for me? What directory to create and what commands to give. I am missing something, but I'm not sure what.

Might not be you. I might need to clarify the docs. We'll figure out for sure where the gap is after I see your output.

**Comment by andy5995** [comment]
I have a feeling this is related to #38 . The Slackbuild script adds some extra flags, such as `-02`. I did some testing in a Slackware 15.0 docker container and had the same results as you.

When I remove the 4 instances of '-02' from the Slackbuild script, the segfault doesn't happen.

With the current git version, the segfault doesn't happen regardless.

I'm going to do a release soon and submit the updated Slackbuild.

Thanks again @aianson

**Comment by aianson** [comment]
On Tue, 09 Aug 2022 13:38:52 -0700
Andy Alt ***@***.***> wrote:

> I have a feeling this is related to #38 . The Slackbuild script adds some extra flags, such as `-02`. I did some testing in a Slackware 15.0 docker container and had the same results as you.
> 
> When I remove the 4 instances of '-02' from the Slackbuild script, the segfault doesn't happen.
> 
> With the current git version, the segfault doesn't happen regardless.

I find the same here with the git version.

> I'm going to do a release soon and submit the updated Slackbuild.

For some reason it is not connecting for me. This is the result when I enter atd"localhost, "telnet localhost" works as expected.

***@***.***:~/src/modemu2k/builddir$ ./modemu2k
modemu2k 0.0.999
Enter 'at%q' to quit

connect()-2: Connection refused

NO CARRIER

**Comment by andy5995** [comment]
> For some reason it is not connecting for me. This is the result when I enter atd"localhost, "telnet localhost" works as expected. ***@***.***:~/src/modemu2k/builddir$ ./modemu2k modemu2k 0.0.999 Enter 'at%q' to quit connect()-2: Connection refused NO CARRIER

I haven't been able to reproduce that yet on my Manjaro system or Slack docker container. 

My results when using the container (I enabled telnetd from /etc/inetd.conf and started rc.inetd):

```
sh-5.1# telnet localhost
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
```

```
modemu2k 0.1.0
Enter 'at%q' to quit

atd"localhost
CONNECT
To escape to command mode, use '+++'.
Use ATO to return to online mode.
recv(): Connection reset by peer

NO CARRIER
at%q
Goodbye.
```

@aianson Could you try the attached file?
[modemu2k-0.1.0.tar.gz](https://github.com/theimpossibleastronaut/modemu2k/files/9301315/modemu2k-0.1.0.tar.gz)


* Once downloaded, rename it to tar.xz instead of tar.gz (I had to rename it... GitHub doesn't support .xz attachments).
* Extract it
* copy the xz file into packaging/Slackbuilds/modemu2k
* run ./modemu2k.Slackbuild

**Comment by aianson** [comment]
On Wed, 10 Aug 2022 08:14:26 -0700
Andy Alt ***@***.***> wrote:

> I haven't been able to reproduce that yet on my Manjaro system or Slack docker container. 
> 
> My results when using the container (I enabled telnetd from /etc/inetd.conf and started rc.inetd):
> 
> ```
> sh-5.1# telnet localhost
> Trying 127.0.0.1...
> Connected to localhost.
> Escape character is '^]'.
> Connection closed by foreign host.
> ```

I have found that "atd"127.0.0.1" succeeds but "atd"localhost" fails.

> @aianson Could you try the attached file?
> [modemu2k-0.1.0.tar.gz](https://github.com/theimpossibleastronaut/modemu2k/files/9301315/modemu2k-0.1.0.tar.gz)

Yes, this works for me. I built modemu2k from that slackbuild and installed it. It is working for me with minicom.

I'm not sure why atd"localhost doesn't work for me but it is unimportant, I'll just use 127.0.0.1 when needed.

Thank you for your work on this. :)

**Comment by andy5995** [comment]
You're welcome, Alan. Thanks for testing the new package.

I've started a new ticket https://github.com/theimpossibleastronaut/modemu2k/issues/44
