### ISSUE TITLE
Comments can be removed

### ISSUE THREAD

**Issue by andy5995** [theimpossibleastronaut/modemu2k#4]
The comments next to these #include statements can be removed. Only the ones near the include statements, the comments below can remain for now.

https://github.com/theimpossibleastronaut/modemu2k/blob/3e0ab8e3200718c556b5af7647e7d81c284dcf37/src/sock.c#L4

**Comment by antwonthegreat** [comment]
On it

**Comment by antwonthegreat** [comment]
All c files or just sock.c?

**Comment by andy5995** [comment]
Just that one for now. I'll need to review the other files before deciding on them. Thanks for asking first.
