### ISSUE TITLE
need Brasilian Portuguese translation of man page

### ISSUE THREAD

**Issue by andy5995** [theimpossibleastronaut/modemu2k#6]
Need Brasilian Portuguese translation of man page

https://github.com/theimpossibleastronaut/modemu2k/blob/master/modemu2k.1

**Comment by Erick2280** [comment]
Can I help with the translation?

**Comment by andy5995** [comment]
Please do. :) you can give it the extensions .1.pt_BR

**Comment by gugacavalieri** [comment]
Need any help with it? @Erick2280

**Comment by Erick2280** [comment]
I finished the translation, but you can check it out if you want :)

**Comment by andy5995** [comment]
Completed by @Erick2280 in https://github.com/theimpossibleastronaut/modemu2k/commit/8969d398f44b2545bc0c4f2500c1b7d6d582e662
